package com.erp.platform.identity.event;

public enum IdentityEventType {
  USER_CREATED,
  USER_UPDATED,
  USER_ACTIVATED,
  USER_DEACTIVATED,
  PASSWORD_CHANGED,
  PASSWORD_RESET,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT,
  ROLE_ASSIGNED,
  ROLE_REMOVED,
  PERMISSION_ASSIGNED,
  PERMISSION_REMOVED,
  CONTEXT_CHANGED,
  TENANT_CREATED,
  ORGANIZATION_CREATED,
  COMPANY_CREATED,
  SESSION_EXPIRED,
  SESSION_REVOKED
}
