export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    me: '/auth/me',
    changePassword: '/auth/change-password',
  },
  context: {
    current: '/context/current',
    options: '/context/options',
    switch: '/context/switch',
  },
  identity: {
    tenants: '/identity/tenants',
    tenant: (id: string) => `/identity/tenants/${id}`,
    organizations: '/identity/organizations',
    organization: (id: string) => `/identity/organizations/${id}`,
    companies: '/identity/companies',
    company: (id: string) => `/identity/companies/${id}`,
    branches: '/identity/branches',
    branch: (id: string) => `/identity/branches/${id}`,
    departments: '/identity/departments',
    department: (id: string) => `/identity/departments/${id}`,
    users: '/identity/users',
    user: (id: string) => `/identity/users/${id}`,
    roles: '/identity/roles',
    role: (id: string) => `/identity/roles/${id}`,
    permissions: '/identity/permissions',
    permission: (id: string) => `/identity/permissions/${id}`,
    sessions: '/identity/sessions',
    session: (id: string) => `/identity/sessions/${id}`,
    audit: '/identity/audit',
  },
  authz: {
    permissions: '/auth/permissions',
    checkPermission: '/auth/check-permission',
    invalidate: '/auth/permissions/invalidate',
  },
  metadata: {
    all: '/metadata',
    models: '/metadata/models',
    views: '/metadata/views',
    workflows: '/metadata/workflows',
  },
  customers: {
    base: '/customers',
    detail: (id: string | number) => `/customers/${id}`,
  },
  users: {
    base: '/users',
    detail: (id: string | number) => `/users/${id}`,
  },
} as const;
